[profile.default]
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200

src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    "forge-std/=lib/forge-std/src/"
]

fuzz_runs = 1000

[profile.ci]
verbosity = 4

gas_reports = ["Echo"]
