[profile.default]
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 200

src = 'src'
out = 'out'
libs = ['lib']
viaIR = true

fuzz_runs = 1000

[profile.ci]
verbosity = 4

gas_reports = ["Echo"]
